VECTORS,COMBINING AND SCALING

In [43]:
# Vectors
import numpy as np
v = np.array([2, 1])
# Create a 2x2 identity matrix representing the standard basis vectors
basis = np.eye(2)
print('Standard Basis Vector:\n',basis)

Standard Basis Vector:
 [[1. 0.]
 [0. 1.]]


Find the standard basis vector for the same vector space

In [44]:


 
u = np.array([6, 5, 8, 11])
 
magnitude_u = np.linalg.norm(u)
unit_vector_u = u / magnitude_u
 
basis_vectors = []
for i in range(len(unit_vector_u)):
    if unit_vector_u[i] != 0:
        basis_vectors.append(np.eye(len(unit_vector_u))[i])
 
basis_vectors = np.array(basis_vectors)
basis_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

SYSTEM OF LINEAR EQUATRIONS AND INVERSE MATRICES

In [45]:
# Solve the given system of equations using the inverse of a matrix.
# 3x+8y=5 equestion 1
# 4x+11y=7
# ​



In [41]:

# Converting the matrix into an array
matrix  = [[3, 8 ], [4, 11]]
A = np.array(matrix)

# Finding the inverse of A
inv_A = np.linalg.inv(A)

print(inv_A)

[[11. -8.]
 [-4.  3.]]


In [42]:
# Converting matrix of B INTO AN ARRAY
B = np.array([5, 7])
#  finding the values for matrix X, using the dot product of the inverse of A and the matrix B
X = np.linalg.inv(A).dot(B)
print(X)

[-1.  1.]


In [ ]:
# 6a + 3b = 27    ## Equation2

# 9a + 4b = 38

In [10]:
matrix  = [[6, 3], [9, 4]]

A = np.array(matrix)
inv_A = np.linalg.inv(A)

print(inv_A)

[[-1.33333333  1.        ]
 [ 3.         -2.        ]]


In [9]:
B = np.array([27,38])

X = np.linalg.inv(A).dot(B)
print(X)

[-7.  6.]


In [11]:
# Matrix decomposition


# Adition
# Program to add two matrices using list comprehension
#Find  A+2B

X = [[-1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[X[i][j] + 2*Y[i][j]  for j in range(len(X[0]))] for i in range(len(X))]

for r in result:
   print(r)

[9, 18, 5]
[16, 19, 12]
[15, 18, 27]


In [47]:
# Matrix decomposition


# subrtact
#Find  A-B

X = [[-1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[X[i][j] + 2*Y[i][j]  for j in range(len(X[0]))] for i in range(len(X))]

for r in result:
   print(r)

[9, 18, 5]
[16, 19, 12]
[15, 18, 27]


DOT PRODUCT

In [13]:


# Define two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Compute the dot product
dot_product = np.dot(a, b)
print(dot_product)  # Output: 32

32


In [14]:
# DOT PRODUCT OF AN ARRAY AND MATRIX
# Define a matrix and an array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array = np.array([2, 2, 2])

# Compute the dot product
dot_product = np.dot(matrix, array)
print(dot_product)  # Output: [12 30 48]

[12 30 48]
